# Generated by Django 4.1.3 on 2022-11-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField()),
                ('clicked_date', models.TextField()),
                ('url', models.TextField(db_column='urL')),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('master_id', models.IntegerField(null=True)),
                ('locale', models.TextField()),
                ('device', models.TextField()),
            ],
            options={
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('unique_clicks', models.IntegerField()),
                ('total_clicks', models.IntegerField()),
                ('timeonpage', models.IntegerField(db_column='timeOnPage', null=True)),
                ('timeonpage_filtered', models.IntegerField(db_column='timeOnPage_filtered', null=True)),
                ('pageBeforeConversion', models.IntegerField(db_column='pageBeforeConversion', null=True)),
                ('pageBeforeShare', models.IntegerField(db_column='pageBeforeShare', null=True)),
                ('device', models.TextField(null=True)),
                ('locale', models.TextField(null=True)),
            ],
            options={
                'db_table': 'urls_metric',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvgEvents',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.events')),
                ('hour', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avgEvents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonsMetric',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.persons')),
                ('clicksToConvert', models.IntegerField(db_column='clicksToConvert', null=True)),
                ('clickstToShare', models.IntegerField(db_column='clicksToShare', null=True)),
                ('timeToConvert', models.IntegerField(db_column='timeToConvert', null=True)),
                ('timeToShare', models.IntegerField(db_column='timeToShare', null=True)),
            ],
            options={
                'db_table': 'persons_metric',
                'managed': False,
            },
        ),
    ]
